Allow failed rpmbuild to be retried -- improved
git-svn-id: https://shorewall.svn.sourceforge.net/svnroot/shorewall/trunk@7240 fbd18981-670d-0410-9b5c-8dc0c1a9a2bb

diff --git a/tools/build/buildshorewall b/tools/build/buildshorewall
--- a/tools/build/buildshorewall
+++ b/tools/build/buildshorewall
@@ -141,9 +141,13 @@ list_search() # $1 = element to search for , $2-$n = list
     return 1
 }
 
+#
+# It's easy to mis-type the GPG passphrase; this function allows us additional chances to get it right
+#
 do_rpmbuild() {
     while ! rpmbuild $@ >> $LOGFILE 2>&1; do
-	echo -n "rpmbuild $@ failed -- Retry? Y/n "
+	echo    "rpmbuild $@ failed" >&2
+	echo -n "Retry? Y/n " >&2
 	read response
 	case $response in
 	    Y*|y*)
