Catch full upload from patch directory
git-svn-id: https://shorewall.svn.sourceforge.net/svnroot/shorewall/trunk@8028 fbd18981-670d-0410-9b5c-8dc0c1a9a2bb

diff --git a/tools/build/upload b/tools/build/upload
--- a/tools/build/upload
+++ b/tools/build/upload
@@ -204,6 +204,11 @@ esac
 
 [ $# -eq 1 ] || { echo "Usage: $(basename $0) <version>"; exit 2; }
 
+if [ -z "$PATCHNUM" -a -d shorewall-common ]; then
+    echo "   ERROR: Paranoid to upload a base release when a patch release has been built in the current directory" >&2
+    exit 1 
+fi
+
 [ -d errata ] || mkdir errata
 
 [ -f known_problems.txt ] || echo "There are no known problems in Shorewall version $1" > known_problems.txt
