Correct typo in error message

diff --git a/Shorewall6/shorewall6 b/Shorewall6/shorewall6
--- a/Shorewall6/shorewall6
+++ b/Shorewall6/shorewall6
@@ -115,7 +115,7 @@ get_config() {
 		    ;;
 		*)
 		    if [ -n "$STARTUP_ENABLED" ]; then
-			echo "   ERROR: Invalid Value for STARTUP_ENABLE: $STARTUP_ENABLED" >&2
+			echo "   ERROR: Invalid Value for STARTUP_ENABLED: $STARTUP_ENABLED" >&2
 			exit 2
 		    fi
 		    ;;
