Fix find_first_interface_address() in IPv6
Signed-off-by: Tom Eastep <teastep@shorewall.net>

diff --git a/Shorewall6/shorewall6 b/Shorewall6/shorewall6
--- a/Shorewall6/shorewall6
+++ b/Shorewall6/shorewall6
@@ -227,16 +227,20 @@ get_config() {
 }
 
 #
+# Issue an error message and die
+#
+startup_error() {
+    echo "   ERROR: $@" >&2
+    kill $$
+    exit 1
+}
+    
+#
 # Run the appropriate compiler
 #
 compiler() {
     pc=${PERLSHAREDIR}/compiler.pl
 
-    startup_error() {
-	echo "   ERROR: $@" >&2
-	exit 1
-    }
-    
     local command
     command=$1
 
