Fix documentation and 'try' command
git-svn-id: https://shorewall.svn.sourceforge.net/svnroot/shorewall/trunk@6385 fbd18981-670d-0410-9b5c-8dc0c1a9a2bb

diff --git a/Shorewall-common/shorewall b/Shorewall-common/shorewall
--- a/Shorewall-common/shorewall
+++ b/Shorewall-common/shorewall
@@ -405,7 +405,7 @@ start_command() {
 	0)
 	    ;;
 	1)
-	    [ -n "$SHOREWALL_DIR" -o -n "$FAST" ] && usage 2
+	    [ -n "$SHOREWALL_DIR" ] && usage 2
 
 	    if [ ! -d $1 ]; then
 		if [ -e $1 ]; then
@@ -983,6 +983,12 @@ try_command() {
 	2)
 	    handle_directory $1
 	    timeout=$2
+	    case $timeout in 
+		*[!0-9]*)
+                    echo "   ERROR: Invalid timeout ($timeout)" >&2;
+		    exit 1
+		    ;;
+	    esac
 	    ;;
 	*)
 	    usage 1
