Remove ill-considered macro
git-svn-id: https://shorewall.svn.sourceforge.net/svnroot/shorewall/trunk@8366 fbd18981-670d-0410-9b5c-8dc0c1a9a2bb

diff --git a/Shorewall-common/shorewall b/Shorewall-common/shorewall
--- a/Shorewall-common/shorewall
+++ b/Shorewall-common/shorewall
@@ -290,8 +290,10 @@ get_config() {
 	    MANGLE_ENABLED=
 	    ;;
 	*)
-	    echo "   ERROR: Invalid MANGLE_ENABLED setting ($MANGLE_ENABLED)" >&2
-	    exit 2
+	    if [ -n "$MANGLE_ENABLED" ]; then
+		echo "   ERROR: Invalid MANGLE_ENABLED setting ($MANGLE_ENABLED)" >&2
+		exit 2
+	    fi
 	    ;;
     esac
 }
