Fix syntax error in /sbin/shorewall
git-svn-id: https://shorewall.svn.sourceforge.net/svnroot/shorewall/trunk@5979 fbd18981-670d-0410-9b5c-8dc0c1a9a2bb

diff --git a/Shorewall-common/shorewall b/Shorewall-common/shorewall
--- a/Shorewall-common/shorewall
+++ b/Shorewall-common/shorewall
@@ -222,6 +222,11 @@ get_config() {
 compiler() {
     local sc=${SHELLSHAREDIR}/compiler
     local pc=${PERLSHAREDIR}/compiler.pl
+
+    startup_error() {
+	echo "   ERROR: $@" >&2
+	exit 1
+    }
     
     local command=$1
 
