Fix a couple of compiler-related bugs
git-svn-id: https://shorewall.svn.sourceforge.net/svnroot/shorewall/trunk@5822 fbd18981-670d-0410-9b5c-8dc0c1a9a2bb

diff --git a/Shorewall-common/shorewall b/Shorewall-common/shorewall
--- a/Shorewall-common/shorewall
+++ b/Shorewall-common/shorewall
@@ -221,7 +221,7 @@ get_config() {
 #
 compiler() {
     fatal_error() {
-	echo "   ERROR: $@" > &2
+	echo "   ERROR: $@" >&2
 	exit 2
     }
     #
@@ -280,6 +280,7 @@ compiler() {
 	    debugflags="-w"
 	    [ -n "$DEBUG" ]   && debugflags='-wd'
 	    [ -n "$PROFILE" ] && DEBUGFLAGS='-wd:DProf'
+	    shift # Perl compiler doesn't need a command
 	    perl $debugflags /usr/share/shorewall-perl/compiler.pl $@
 	    ;;
 	shell)
