Enhanced operational logging
git-svn-id: https://shorewall.svn.sourceforge.net/svnroot/shorewall/trunk@7729 fbd18981-670d-0410-9b5c-8dc0c1a9a2bb

diff --git a/Shorewall-common/shorewall b/Shorewall-common/shorewall
--- a/Shorewall-common/shorewall
+++ b/Shorewall-common/shorewall
@@ -224,7 +224,30 @@ get_config() {
 
 	export LOGFORMAT
 
-    fi
+	if [ -n "$STARTUP_LOG" ]; then
+	    if [ -n "$LOG_VERBOSITY" ]; then
+		case $LOG_VERBOSITY in
+		    -1)
+			;;
+		    0|1|2)
+			[ -n "$STARTUP_LOG" ] || $LOG_VERBOSITY=-1;
+			;;
+		    *)
+		        echo "  ERROR: INvalid LOG_VERBOSITY ($LOG_VERBOSITY)" >&2
+			exit 2;
+			;;
+		esac
+	    else
+		$LOG_VERBOSITY=2;
+	    fi
+	else
+	    LOG_VERBOSITY=-1;
+	fi
+
+    else
+	STARTUP_LOG=
+	LOG_VERBOSITY=-1
+    fi   
 
     if [ -n "$SHOREWALL_SHELL" ]; then
 	if [ ! -x "$SHOREWALL_SHELL" ]; then
@@ -235,7 +258,7 @@ get_config() {
 
     [ -n "${VERBOSITY:=2}" ]
 
-    VERBOSE=$(($VERBOSE_OFFSET + $VERBOSITY))
+    [ -n "$USE_VERBOSITY" ] && VERBOSE=$USE_VERBOSITY || VERBOSE=$(($VERBOSE_OFFSET + $VERBOSITY))
 
     export VERBOSE
 
@@ -315,6 +338,15 @@ compiler() {
 	fi
     fi
 
+    case $COMMAND in
+	*start|try|refresh)
+	    ;;
+	*)
+	    STARTUP_LOG=
+	    LOG_VERBOSITY=-1
+	    ;;
+    esac
+
     [ $command = exec ] || command=
     
     case "$compiler" in
@@ -329,12 +361,14 @@ compiler() {
 	    [ "$1" = nolock ] && shift;
 	    shift 
 
-	    options="--verbose $VERBOSE ";
+	    options="--verbose=$VERBOSE "
+	    [ -n "$STARTUP_LOG" ] && options="$options --log=$STARTUP_LOG "
+	    [ -n "$LOG_VERBOSITY" ] && options="$options --log_verbosity=$LOG_VERBOSITY ";
 	    [ -n "$EXPORT" ] && options="$options --export "
-	    [ -n "$SHOREWALL_DIR" ] && options="$options --directory $SHOREWALL_DIR "
+	    [ -n "$SHOREWALL_DIR" ] && options="$options --directory=$SHOREWALL_DIR "
 	    [ -n "$TIMESTAMP" ] && options="$options --timestamp "
 	    [ "$debugging" = trace ] && options="$options --debug "
-	    [ -n "$REFRESHCHAINS" ] && options="$options --refresh $REFRESHCHAINS"
+	    [ -n "$REFRESHCHAINS" ] && options="$options --refresh=$REFRESHCHAINS"
 	    [ -x $pc ] || startup_error "SHOREWALL_COMPILER=perl requires the shorewall-perl package which is not installed"
 	    #
 	    # Run the appropriate params file
@@ -348,6 +382,8 @@ compiler() {
 	    $command perl $debugflags $pc $options $@
 	    ;;
 	shell)
+	    LOG_VERBOSE=$LOG_VERBOSITY
+	    export STARTUP_LOG LOG_VERBOSE
 	    [ -x $sc ] || startup_error "SHOREWALL_COMPILER=shell requires the shorewall-shell package which is not installed"
 	    [ -n "$REFRESHCHAINS" ] && startup_error "Shorewall-shell does not support refresh of specific chains"
 	    $command $SHOREWALL_SHELL $sc $@
@@ -406,6 +442,10 @@ start_command() {
 			    SHOREWALL_COMPILER=$2
 			    option=
 			    shift
+			    ;;
+			d*)
+			    DEBUG=Yes
+			    option=${option#d}
 			    ;;
 			f*)
 			    FAST=Yes
@@ -668,6 +708,10 @@ restart_command() {
 			-)
 			    finished=1
 			    option=
+			    ;;
+			d*)
+			    DEBUG=Yes
+			    option=${option#d}
 			    ;;
 			n*)
 			    NOROUTES=Yes
@@ -1332,6 +1376,7 @@ SHOREWALL_DIR=
 IPT_OPTIONS="-nv"
 FAST=
 VERBOSE_OFFSET=0
+USE_VERBOSITY=
 NOROUTES=
 EXPORT=
 export TIMESTAMP=
@@ -1383,8 +1428,29 @@ while [ $finished -eq 0 ]; do
 			option=${option#f}
 			;;
 		    v*)
-			VERBOSE_OFFSET=$(($VERBOSE_OFFSET + 1 ))
 			option=${option#v}
+			case $option in 
+			    -1*)
+				USE_VERBOSITY=-1
+				option=${option#-1}
+				;;
+			    0*)
+				USE_VERBOSITY=0
+				option=${option#0}
+				;;
+			    1*)
+				USE_VERBOSITY=1
+				option=${option#1}
+				;;
+			    2*)
+				USE_VERBOSITY=2
+				option=${option#2}
+				;;
+			    *)
+				VERBOSE_OFFSET=$(($VERBOSE_OFFSET + 1 ))
+				USE_VERBOSITY=
+				;;
+			esac
 			;;
 		    n*)
 			NOROUTES=Yes
