More save fixes
git-svn-id: https://shorewall.svn.sourceforge.net/svnroot/shorewall/trunk@1299 fbd18981-670d-0410-9b5c-8dc0c1a9a2bb

diff --git a/Shorewall2/firewall b/Shorewall2/firewall
--- a/Shorewall2/firewall
+++ b/Shorewall2/firewall
@@ -108,6 +108,30 @@ save_command()
 }
 
 #
+# Save the passed command in the restore script then run it -- returns the status of the command
+# If the command involves file redirection then it must be enclosed in quotes as in:
+#
+#     run_and_save_command "echo 1 > /proc/sys/net/ipv4/ip_forward"
+#
+run_and_save_command() 
+{
+    echo "$@" >> /var/lib/shorewall/restore-$$
+    eval $*
+}
+
+#
+# Run the passed command and if it succeeds, save it in the restore script. If it fails, stop the firewall and die
+#
+ensure_and_save_command() 
+{
+    if eval $* ; then
+	echo "$@" >> /var/lib/shorewall/restore-$$
+    else
+	[ -z "$stopping" ] && { stop_firewall; exit 2; }
+    fi
+}
+    
+#
 # Append a file to /var/lib/shorewall/restore-$$
 #
 append_file() {
@@ -1155,13 +1179,11 @@ log_rule() # $1 = log level, $2 = chain, $3 = disposition , $... = predicates fo
 setup_forwarding() {
     case "$IP_FORWARDING" in
     [Oo][Nn])
-	echo 1 > /proc/sys/net/ipv4/ip_forward
-	save_command "echo 1 > /proc/sys/net/ipv4/ip_forward"
+	run_and_save_command "echo 1 > /proc/sys/net/ipv4/ip_forward"
 	echo "IP Forwarding Enabled"
 	;;
     [Oo][Ff][Ff])
-	echo 0 > /proc/sys/net/ipv4/ip_forward
-	save_command "echo 0 > /proc/sys/net/ipv4/ip_forward"
+	run_and_save_command "echo 0 > /proc/sys/net/ipv4/ip_forward"
 	echo "IP Forwarding Disabled!"
 	;;
     esac
@@ -1594,19 +1616,14 @@ setup_proxy_arp() {
 	esac
 
 	if [ -z "$haveroute" ]; then
-	    run_ip route replace $address dev $interface
-	    save_command ip route replace $address dev $interface
+	    ensure_and_save_command ip route replace $address dev $interface
 	    [ -n "$persistent" ] && haveroute=yes
 	fi
 
-	run_arp -i $external -Ds $address $external pub
+	ensure_and_save_command arp -i $external -Ds $address $external pub
 
-	echo 1 > /proc/sys/net/ipv4/conf/$interface/proxy_arp
-	echo 0 > /proc/sys/net/ipv4/conf/$external/proxy_arp
-
-	save_command arp -i $external -Ds $address $external pub
-	save_command "echo 1 > /proc/sys/net/ipv4/conf/$interface/proxy_arp"
-	save_command "echo 0 > /proc/sys/net/ipv4/conf/$external/proxy_arp"
+	run_and_save_command "echo 1 > /proc/sys/net/ipv4/conf/$interface/proxy_arp"
+	run_and_save_command "echo 0 > /proc/sys/net/ipv4/conf/$external/proxy_arp"
 
 	echo $address $interface $external $haveroute >> ${STATEDIR}/proxyarp
 
@@ -1821,8 +1838,7 @@ setup_nat() {
 	iface=${interface%:*}
 
 	if [ -n "$ADD_IP_ALIASES" ]; then
-	    qt ip addr del $external dev $iface
-	    save_command qt ip addr del $external dev $iface
+	    run_and_save_command qt ip addr del $external dev $iface
 	fi
 
 	if [ "x$allints" = "xYes" -o "$xallints" = "xyes" ]; then
@@ -2071,6 +2087,7 @@ setup_tc1() {
     run_iptables -t mangle -A OUTPUT     -j tcout
 
     run_user_exit tcstart
+    save_command . $(find_file tcstart)
 
 }
 
@@ -2088,8 +2105,9 @@ delete_tc()
 {
 
     clear_one_tc() {
-	tc qdisc del dev $1 root    2> /dev/null
-	tc qdisc del dev $1 ingress 2> /dev/null
+	run_and_save_command "tc qdisc del dev $1 root 2> /dev/null"
+	run_and_save_command "tc qdisc del dev $1 ingress 2> /dev/null" 
+
     }
 
     run_user_exit tcclear
@@ -4435,8 +4453,7 @@ add_ip_aliases()
     do_one()
     {
 	val=$(address_details)
-	run_ip addr add ${external}${val} dev $interface $label
-	save_command ip addr add ${external}${val} dev $interface $label
+	ensure_and_save_command ip addr add ${external}${val} dev $interface $label
 	echo "$external $interface" >> ${STATEDIR}/nat
 	[ -n "$label" ] && label="with $label"
 	progress_message "   IP Address $external added to interface $interface $label"
@@ -4936,8 +4953,7 @@ add_common_rules() {
     # ARP Filtering
     #
     for f in /proc/sys/net/ipv4/conf/*/arp_filter; do
-	echo 0 > $f
-	save_command "echo 0 > $f"
+	run_and_save_command "echo 0 > $f"
     done
 
     interfaces=$(find_interfaces_by_option arp_filter)
@@ -4948,8 +4964,7 @@ add_common_rules() {
 	for interface in $interfaces; do
 	    file=/proc/sys/net/ipv4/conf/$interface/arp_filter
 	    if [ -f $file ]; then
-		echo 1 > $file
-		save_command "echo 1 > $file"
+		run_and_save_command "echo 1 > $file"
 	    else
 		error_message \
 		    "Warning: Cannot set ARP filtering on $interface"
@@ -4965,31 +4980,26 @@ add_common_rules() {
 	echo "Setting up Kernel Route Filtering..."
 
 	for f in /proc/sys/net/ipv4/conf/*/rp_filter; do
-	    echo 0 > $f
-	    save_command "echo 0 > $f"
+	    run_and_save_command "echo 0 > $f"
 	done
 
 	for interface in $interfaces; do
 	    file=/proc/sys/net/ipv4/conf/$interface/rp_filter
 	    if [ -f $file ]; then
-		echo 1 > $file
-		save_command "echo 1 > $file"
+		run_and_save_command "echo 1 > $file"
 	    else
 		error_message \
 		    "Warning: Cannot set route filtering on $interface"
 	    fi
 	done
 	
-	echo 1 > /proc/sys/net/ipv4/conf/all/rp_filter
-	save_command "echo 1 > /proc/sys/net/ipv4/conf/all/rp_filter"
+	run_and_save_command "echo 1 > /proc/sys/net/ipv4/conf/all/rp_filter"
 
 	if [ -n "$ROUTE_FILTER" ]; then
-	    echo 1 > /proc/sys/net/ipv4/conf/default/rp_filter
-	    save_command "echo 1 > /proc/sys/net/ipv4/conf/default/rp_filter"
+	    run_and_save_command "echo 1 > /proc/sys/net/ipv4/conf/default/rp_filter"
 	fi
 
-	run_ip route flush cache
-	save_command ip route flush cache
+	run_and_save_command ip route flush cache
     fi
 
     if [ -n "$DYNAMIC_ZONES" ]; then
