Add dropInvalid builtin action
git-svn-id: https://shorewall.svn.sourceforge.net/svnroot/shorewall/trunk@1430 fbd18981-670d-0410-9b5c-8dc0c1a9a2bb

diff --git a/Shorewall2/functions b/Shorewall2/functions
--- a/Shorewall2/functions
+++ b/Shorewall2/functions
@@ -374,10 +374,10 @@ mktempfile() {
 		mktemp -p $1 shorewall.XXXXXX
 		;;
 	    None)
-		mkdir $1/shorewall-$$ && echo $1/shorewall-$$
+		> $1/shorewall-$$ && echo $1/shorewall-$$
 		;;
 	    *)
-		echo "   ERROR:Internal error in mktempfile"
+		echo "   ERROR:Internal error in mktempfile" >&2
 		;;
 	esac
     else
@@ -393,7 +393,7 @@ mktempfile() {
 		> /tmp/shorewall-$$ && echo /tmp/shorewall-$$
 		;;
 	    *)
-		echo "   ERROR:Internal error in mktempfile"
+		echo "   ERROR:Internal error in mktempfile" >&2
 		;;
 	esac
     fi
@@ -407,17 +407,17 @@ mktempdir() {
     [ -z "$MKTEMP" ] && find_mktemp   
      
     case "$MKTEMP" in
-	BSD)
-	    mktemp -d /tmp/shorewall.XXXXXX
-	    ;;
 	STD)
 	    mktemp -td shorewall.XXXXXX
 	    ;;
-	None)
-	    mkdir /tmp/shorewall-$$ && echo /tmp/shorewall-$$
+	None|BSD)
+	    #
+	    # Not all versions of the BSD mktemp support the -d option under Linux
+	    #
+	    mkdir /tmp/shorewall-$$ && chmod 700 /tmp/shorewall-$$ && echo /tmp/shorewall-$$
 	    ;;
 	*)
-	    echo "   ERROR:Internal error in mktempdir"
+	    echo "   ERROR:Internal error in mktempdir" >&2
 	    ;;
 	esac
 }	
@@ -767,3 +767,11 @@ find_interface_by_address() {
     [ -n "$dev" ] && echo $dev
 }
 
+#
+# Find interface addresses--returns the set of addresses assigned to the passed
+# device
+#
+find_interface_addresses() # $1 = interface
+{
+    ip -f inet addr show $1 | grep inet | sed 's/inet //;s/\/.*//;s/ peer.*//'
+}
