Add /usr/share/shorewall/configpath file
git-svn-id: https://shorewall.svn.sourceforge.net/svnroot/shorewall/trunk@1263 fbd18981-670d-0410-9b5c-8dc0c1a9a2bb

diff --git a/Shorewall2/functions b/Shorewall2/functions
--- a/Shorewall2/functions
+++ b/Shorewall2/functions
@@ -83,6 +83,17 @@ fix_bang() {
 }
 
 #
+# Set default config path
+#
+ensure_config_path() {
+    local F=/usr/share/shorewall/configpath
+    if [ -z "$CONFIG_PATH" ]; then
+	[ -f $F ] || { echo "   ERROR: $F does not exist"; exit 2; }
+	. $F
+    fi
+}
+   
+#
 # Find a File -- For relative file name, look first in $SHOREWALL_DIR then in /etc/shorewall
 #
 find_file()
@@ -495,14 +506,14 @@ in_network() # $1 = IP address, $2 = CIDR network
 ip_vlsm() {
     local mask=$(decodeaddr $1)
     local vlsm=0
-    local x=$(( 128 $LEFTSHIFT 24 ))
+    local x=$(( 128 $LEFTSHIFT 24 )) # 0x80000000
 
     while [ $(( $x & $mask )) -ne 0 ]; do
-	[ $mask -eq $x ] && mask=0 || mask=$(( $mask $LEFTSHIFT 1 )) # Don't Ask...
+	[ $mask -eq $x ] && mask=0 || mask=$(( $mask $LEFTSHIFT 1 )) # Not all shells shift 0x80000000 left properly.
 	vlsm=$(($vlsm + 1))
     done
 
-    if [ $(( $mask & 2147483647)) -ne 0 ]; then
+    if [ $(( $mask & 2147483647 )) -ne 0 ]; then # 2147483647 = 0x7fffffff
 	echo "Invalid net mask: $1" >&2
     else
 	echo $vlsm
