Remove DYNAMIC_ZONES dependency for 'show zones'
git-svn-id: https://shorewall.svn.sourceforge.net/svnroot/shorewall/trunk@1782 fbd18981-670d-0410-9b5c-8dc0c1a9a2bb

diff --git a/Shorewall2/shorewall b/Shorewall2/shorewall
--- a/Shorewall2/shorewall
+++ b/Shorewall2/shorewall
@@ -927,7 +927,7 @@ case "$1" in
 		done < $STATEDIR/zones
 		echo
 	    else
-		echo "   ERROR: Dynamic zones are not enabled" >&2
+		echo "   ERROR: $STATEDIR/zones does not exist" >&2
 		exit 1
 	    fi
 	    ;;
