Make a couple of more warnings more emphatic
git-svn-id: https://shorewall.svn.sourceforge.net/svnroot/shorewall/trunk@2438 fbd18981-670d-0410-9b5c-8dc0c1a9a2bb

diff --git a/Shorewall/functions b/Shorewall/functions
--- a/Shorewall/functions
+++ b/Shorewall/functions
@@ -178,7 +178,7 @@ separate_list() {
 	    #
             [ -n "$terminator" ] && \
 		$terminator "Invalid comma-separated list \"$@\""
-            echo "Warning -- invalid comma-separated list \"$@\"" >&2
+            echo "WARNING -- invalid comma-separated list \"$@\"" >&2
 	    ;;
 	*\[*\]*)
 	    #
@@ -431,7 +431,7 @@ read_file() # $1 = file name, $2 = nest count
 	done < $1
     else
 	[ -n "$terminator" ] && $terminator "No such file: $1"
-	echo "Warning -- No such file: $1"
+	echo "WARNING -- No such file: $1"
     fi
 }
 
