More modularization
git-svn-id: https://shorewall.svn.sourceforge.net/svnroot/shorewall/trunk@4381 fbd18981-670d-0410-9b5c-8dc0c1a9a2bb

diff --git a/Shorewall/shorewall b/Shorewall/shorewall
--- a/Shorewall/shorewall
+++ b/Shorewall/shorewall
@@ -1681,11 +1681,12 @@ FIREWALL=$SHAREDIR/firewall
 FUNCTIONS=$SHAREDIR/functions
 VERSION_FILE=$SHAREDIR/version
 HELP=$SHAREDIR/help
+LIBRARIES="base"
 
 if [ -f $FUNCTIONS ]; then
-    . $FUNCTIONS
+    . $FUNCTIONS $LIBRARIES
 else
-    echo "$FUNCTIONS does not exist!" >&2
+    echo "   ERROR: $FUNCTIONS does not exist!" >&2
     exit 2
 fi
 
