Move firewall, functions and version to /var/lib/shorewall
git-svn-id: https://shorewall.svn.sourceforge.net/svnroot/shorewall/trunk@73 fbd18981-670d-0410-9b5c-8dc0c1a9a2bb

diff --git a/Shorewall/shorewall b/Shorewall/shorewall
--- a/Shorewall/shorewall
+++ b/Shorewall/shorewall
@@ -480,21 +480,18 @@ if [ $# -eq 0 ]; then
     usage 1
 fi
 
-functions=/etc/shorewall/functions
+[ -n "$SHOREWALL_DIR" ] && export SHOREWALL_DIR
 
-if [ -n "$SHOREWALL_DIR" ]; then
-   export SHOREWALL_DIR
-   [ -f $SHOREWALL_DIR/functions ] && functions=$SHOREWALL_DIR/functions
-fi
+functions=/var/lib/shorewall/functions
 
 if [ -f $functions ]; then
     . $functions
 else
-    echo "/etc/shorewall/functions does not exist!" >&2
+    echo "$functions does not exist!" >&2
     exit 2
 fi
 
-firewall=`find_file firewall`
+firewall=/var/lib/shorewall/firewall
 
 if [ ! -f $firewall ]; then
     echo "ERROR: Shorewall is not properly installed"
@@ -502,7 +499,7 @@ if [ ! -f $firewall ]; then
 	echo "       $firewall is a symbolic link to a"
 	echo "       non-existant file"
     else
-	echo "       The file /etc/shorewall/firewall does not exist"
+	echo "       The file /var/lib/shorewall/firewall does not exist"
     fi
 
     exit 2
@@ -510,13 +507,13 @@ fi
 
 PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin
 
-version_file=`find_file version`
+version_file=/var/lib/shorewall/version
 
 if [ -f $version_file ]; then
     version=`cat $version_file`
 else
-    echo "ERROR: Shoreline Firewall is not properly installed"
-    echo "       The file /etc/shorewall/version does not exist"
+    echo "ERROR: Shorewall is not properly installed"
+    echo "       The file /var/lib/shorewall/version does not exist"
     exit 1
 fi
 
