More fixing of exit status
git-svn-id: https://shorewall.svn.sourceforge.net/svnroot/shorewall/trunk@5428 fbd18981-670d-0410-9b5c-8dc0c1a9a2bb

diff --git a/Shorewall/shorewall b/Shorewall/shorewall
--- a/Shorewall/shorewall
+++ b/Shorewall/shorewall
@@ -233,8 +233,8 @@ start_command() {
 	    ${VARDIR}/.start $debugging start
 	    rc=$?
 	else
-	    logger -p kern.err "ERROR:Shorewall start failed"
 	    rc=$?
+	    logger -p kern.err "ERROR:Shorewall start failed"
 	fi
 
 	[ -n "$nolock" ] || mutex_off
@@ -617,7 +617,11 @@ refresh_command() {
 	$SHOREWALL_SHELL ${VARDIR}/.refresh $debugging refresh
     fi
 
+    rc=$?
+
     [ -n "$nolock" ] || mutex_off
+
+    return $rc
 }
 
 #
