Recode fix for find_first_interface_address()
Signed-off-by: Tom Eastep <teastep@shorewall.net>

diff --git a/Shorewall/shorewall b/Shorewall/shorewall
--- a/Shorewall/shorewall
+++ b/Shorewall/shorewall
@@ -301,14 +301,19 @@ get_config() {
 }
 
 #
+# Fatal error
+#
+startup_error() {
+    echo "   ERROR: $@" >&2
+    kill $$
+    exit 1
+}
+
+#
 # Run the compiler
 #
 compiler() {
-    startup_error() {
-	echo "   ERROR: $@" >&2
-	exit 1
-    }
-    
+   
     if [ $(id -u) -ne 0 ]; then
 	if [ -z "$SHOREWALL_DIR" -o "$SHOREWALL_DIR" = /etc/shorewall ]; then
 	    startup_error "Ordinary users may not compile the /etc/shorewall configuration"
