Copy latest 2.4 version from Shorewall2/
git-svn-id: https://shorewall.svn.sourceforge.net/svnroot/shorewall/trunk@2264 fbd18981-670d-0410-9b5c-8dc0c1a9a2bb

diff --git a/Shorewall/shorewall b/Shorewall/shorewall
--- a/Shorewall/shorewall
+++ b/Shorewall/shorewall
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-#     Shorewall Packet Filtering Firewall Control Program - V2.2
+#     Shorewall Packet Filtering Firewall Control Program - V2.4
 #
 #     This program is under GPL [http://www.gnu.org/copyleft/gpl.htm]
 #
@@ -97,6 +97,14 @@
 #          shorewall iprange <address>-<address>   Decomposes a range of IP addresses into
 #                                                  a list of network/host addresses.
 #
+#          shorewall safe-start                    Starts the firewall and promtp for a c
+#                                                  confirmation to accept or reject the new 
+#                                                  configuration
+#
+#          shorewall safe-restart                  Restarts the firewall and prompt for a 
+#                                                  confirmation to accept or reject the new 
+#                                                  configuration
+#
 # Fatal Error
 #
 fatal_error() # $@ = Message
@@ -136,7 +144,7 @@ showchain() # $1 = name of chain
 }
 
 #
-# The 'awk' hack that compensates for a bug in iptables-save (actually in libipt_policy.so) and can be removed when that bug is fixed.
+# The 'awk' hack that compensates for bugs in iptables-save (or rather in the extension modules).
 #
 
 iptablesbug()
@@ -146,6 +154,7 @@ iptablesbug()
              /^-j/           { print sline $0; next };\
              /-m policy.*-j/ { print $0; next };\
              /-m policy/     { sline=$0; next };\
+             /--mask ff/     { sub( /--mask ff/, "--mask 0xff" ) };\
                              {print ; sline="" }'
     else
 	echo "   Warning: You don't have 'awk' on this system so the output of the save command may be unusable" >&2
@@ -590,6 +599,88 @@ logwatch() # $1 = timeout -- if negative, prompt each time that
 }
 
 #
+# Save currently running configuration
+#
+save_config() {
+    [ "$nolock" ] || mutex_on
+
+    if qt $IPTABLES -L shorewall -n; then
+	[ -d /var/lib/shorewall ] || mkdir -p /var/lib/shorewall
+	
+	if [ -f $RESTOREPATH -a ! -x $RESTOREPATH ]; then
+	    echo "   ERROR: $RESTOREPATH exists and is not a saved Shorewall configuration"
+	else
+	    case $RESTOREFILE in
+		save|restore-base)
+		    echo "   ERROR: Reserved file name: $RESTOREFILE"
+		    ;;
+		*)
+		    if $IPTABLES -L dynamic -n > /var/lib/shorewall/save; then
+			echo "   Dynamic Rules Saved"
+			if [ -f /var/lib/shorewall/restore-base ]; then
+			    cp -f /var/lib/shorewall/restore-base /var/lib/shorewall/restore-$$
+			    if iptables-save | iptablesbug >> /var/lib/shorewall/restore-$$ ; then
+				echo __EOF__ >> /var/lib/shorewall/restore-$$
+				[ -f /var/lib/shorewall/restore-tail ] && \
+				    cat /var/lib/shorewall/restore-tail >> /var/lib/shorewall/restore-$$
+				mv -f /var/lib/shorewall/restore-$$ $RESTOREPATH 
+				chmod +x $RESTOREPATH
+				echo "   Currently-running Configuration Saved to $RESTOREPATH"
+				
+				rm -f ${RESTOREPATH}-ipsets
+				    
+				case ${SAVE_IPSETS:-No} in
+				    [Yy][Ee][Ss])
+                                        RESTOREPATH=${RESTOREPATH}-ipsets
+
+					f=/var/lib/shorewall/restore-$$
+
+					echo "#!/bin/sh" > $f
+					echo "#This ipset restore file generated $(date) by Shorewall $version" >> $f
+					echo  >> $f
+					echo ". /usr/share/shorewall/functions" >> $f
+					echo  >> $f
+					grep '^MODULE' /var/lib/shorewall/restore-base >>  $f
+					echo "reload_kernel_modules << __EOF__" >> $f
+					grep 'loadmodule ip_set' /var/lib/shorewall/restore-base >>  $f
+                                        echo "__EOF__" >> $f
+					echo  >> $f
+					echo "ipset -U :all: :all:" >> $f
+					echo "ipset -F" >> $f
+					echo "ipset -X" >> $f
+					echo "ipset -R << __EOF__" >> $f
+					ipset -S >> $f
+					echo "__EOF__" >> $f
+					mv -f $f $RESTOREPATH 
+					chmod +x $RESTOREPATH
+					echo "   Current Ipset Contents Saved to $RESTOREPATH"
+					;;
+				    [Nn][Oo])
+				        ;;
+				    *)
+				        echo "   WARNING: Invalid value ($SAVE_IPSETS) for SAVE_IPSETS. Ipset contents not saved"
+					;;
+				esac
+			    else
+			        rm -f /var/lib/shorewall/restore-$$
+				echo "   ERROR: Currently-running Configuration Not Saved"
+			    fi
+			else
+			    echo "   ERROR: /var/lib/shorewall/restore-base does not exist"
+			fi
+		    else
+		        echo "Error Saving the Dynamic Rules"
+		    fi
+		    ;;
+	    esac
+	fi
+    else
+	echo "Shorewall isn't started"
+    fi
+    
+    [ "$nolock" ] || mutex_off
+}
+#
 # Help information
 #
 help()
@@ -630,6 +721,8 @@ usage() # $1 = exit status
     echo "   status"
     echo "   try <directory> [ <timeout> ]"
     echo "   version"
+    echo "   safe-start"
+    echo "   safe-restart"
     echo 
     exit $1
 }
@@ -642,12 +735,34 @@ show_reset() {
 	echo "Counters reset $(cat $STATEDIR/restarted)" && \
 	echo
 }
+
 #
 # Display's the passed file name followed by "=" and the file's contents.
 #
 show_proc() # $1 = name of a file  
 {
     [ -f $1 ] && echo "   $1 = $(cat $1)"
+}
+
+read_yesno_with_timeout() { 
+    read -t 60 yn 2> /dev/null
+    if [ $? -eq 2 ]
+    then
+	# read doesn't support timeout
+	test -x /bin/bash || return 2 # bash is not installed so the feature is not available
+	/bin/bash -c 'read -t 60 yn ; if [ "$yn" == "y" ] ; then exit 0 ; else exit 1 ; fi' # invoke bash and use its version of read
+	return $?
+    else
+	# read supports timeout
+	case "$yn" in
+	    y|Y)
+		return 0
+		;;
+	    *)
+		return 1
+		;;
+	esac
+    fi
 }
 
 #
@@ -846,6 +961,17 @@ case "$1" in
 	    RESTOREPATH=/var/lib/shorewall/$RESTOREFILE
 
 	    if [ -x $RESTOREPATH ]; then
+		if [ -x ${RESTOREPATH}-ipsets ]; then
+		    echo Restoring Ipsets...
+		    #
+		    # We must purge iptables to be sure that there are no
+		    # references to ipsets
+		    #
+		    iptables -F
+		    iptables -X
+		    ${RESTOREPATH}-ipsets
+		fi
+
 		echo Restoring Shorewall...
 		$RESTOREPATH
 		date > $STATEDIR/restarted
@@ -1035,7 +1161,8 @@ case "$1" in
 	    echo
 	    ip rule ls
 	    ip rule ls | while read rule; do
-		table=${rule##* }
+		echo ${rule##* }
+	    done | sort -u | while read table; do 
 		echo
 		echo "Table $table:"
 		echo
@@ -1187,47 +1314,8 @@ case "$1" in
 
 	RESTOREPATH=/var/lib/shorewall/$RESTOREFILE
 
-	mutex_on
+	save_config
 
-	if qt $IPTABLES -L shorewall -n; then
-	    [ -d /var/lib/shorewall ] || mkdir -p /var/lib/shorewall
-
-	    if [ -f $RESTOREPATH -a ! -x $RESTOREPATH ]; then
-		echo "   ERROR: $RESTOREPATH exists and is not a saved Shorewall configuration"
-	    else
-		case $RESTOREFILE in
-		    save|restore-base)
-			echo "   ERROR: Reserved file name: $RESTOREFILE"
-			;;
-		    *)
-			if $IPTABLES -L dynamic -n > /var/lib/shorewall/save; then
-			    echo "   Dynamic Rules Saved"
-			    if [ -f /var/lib/shorewall/restore-base ]; then
-				cp -f /var/lib/shorewall/restore-base /var/lib/shorewall/restore-$$
-				if iptables-save | iptablesbug >> /var/lib/shorewall/restore-$$ ; then
-				    echo __EOF__ >> /var/lib/shorewall/restore-$$
-				    [ -f /var/lib/shorewall/restore-tail ] && \
-					cat /var/lib/shorewall/restore-tail >> /var/lib/shorewall/restore-$$
-				    mv -f /var/lib/shorewall/restore-$$ $RESTOREPATH 
-				    chmod +x $RESTOREPATH
-				    echo "   Currently-running Configuration Saved to $RESTOREPATH"
-				else
-				    rm -f /var/lib/shorewall/restore-$$
-				    echo "   ERROR: Currently-running Configuration Not Saved"
-				fi
-			    else
-				echo "   ERROR: /var/lib/shorewall/restore-base does not exist"
-			    fi
-			else
-			    echo "Error Saving the Dynamic Rules"
-			fi
-			;;
-		esac
-	    fi
-	else
-	    echo "Shorewall isn't started"
-	fi
-	mutex_off
 	;;
     forget)
 	case $# in
@@ -1246,6 +1334,12 @@ case "$1" in
 	RESTOREPATH=/var/lib/shorewall/$RESTOREFILE
 
 	if [ -x $RESTOREPATH ]; then
+
+	    if [ -x ${RESTOREPATH}-ipsets ]; then
+		rm -f ${RESTOREPATH}-ipsets
+		echo "    ${RESTOREPATH}-ipsets removed"
+	    fi
+
 	    rm -f $RESTOREPATH
 	    echo "    $RESTOREPATH removed"
 	elif [ -f $RESTOREPATH ]; then
@@ -1302,11 +1396,22 @@ case "$1" in
 
 	RESTOREPATH=/var/lib/shorewall/$RESTOREFILE
 
-	if [ -x $RESTOREPATH ]; then
+	[ -n "$nolock" ] || mutex_on
+
+	if [ -x $RESTOREPATH ]; then 
+	    if [ -x ${RESTOREPATH}-ipsets ] ; then
+		echo Restoring Ipsets...
+		iptables -F
+		iptables -X
+		${RESTOREPATH}-ipsets
+	    fi
+
 	    echo Restoring Shorewall...
 	    $RESTOREPATH && echo "Shorewall restored from /var/lib/shorewall/$RESTOREFILE"
+	    [ -n "$nolock" ] || mutex_off
 	else
 	    echo "File /var/lib/shorewall/$RESTOREFILE: file not found"
+	    [ -n "$nolock" ] || mutex_off
             exit 2
         fi
         ;;
@@ -1322,6 +1427,76 @@ case "$1" in
 	shift
 	[ $# -ne 1 ] && usage 1
 	help $@
+	;;
+    safe-restart|safe-start)
+	# test is the shell supports timed read 
+	read -t 0 junk 2> /dev/null
+	if [ $? -eq 2 -a ! -x /bin/bash ]
+	then
+	    echo "Your shell does not support a feature required to execute this command".
+	    exit 2
+	fi
+
+	mutex_on
+
+	if qt $IPTABLES -L shorewall -n 
+	then
+	    running=0
+	else
+	    running=1
+	fi
+
+	if [ "$1" = "safe-start" -a  $running -eq 0 ]
+	then
+	    # the command is safe-start but the firewall is already running
+	    $0 nolock $debugging start
+	    ret=$?
+	    exit 0
+	fi
+	
+	if [ "$1" = "safe-start" -o  $running -ne 0 ]
+	then
+	    # the command is safe-start or shorewall is not started yet
+	    command="start"
+	else
+	    # the command is safe-restart and the firewall is already running 
+	    command="restart"
+	fi
+
+	if [ "$command" = "restart" ]
+	then
+	    # save previous configuration
+	    $0 nolock $debugging save "safe-start-restart"
+	fi
+
+	$0 nolock $debugging $command
+
+	echo -n "Do you want to accept the new firewall configuration? [y/n] "
+	read_yesno_with_timeout
+	if [ $? -eq 0 ]
+	then
+	    echo "New configuration has been accepted"
+	    if [ "$command" = "restart" ]
+	    then
+		# removed previous configuration
+		rm /var/lib/shorewall/safe-start-restart
+	    fi
+	else	
+	    if [ "$command" = "restart" ]
+	    then
+		$0 nolock $debugging restore "safe-start-restart"
+		rm /var/lib/shorewall/safe-start-restart
+	    else		    
+		$0 nolock $debugging clear
+	    fi
+	    
+	    mutex_off
+	    echo "New configuration has been rejected and the old one restored"
+	    exit 2
+	fi
+
+	mutex_off
+	[ $? -eq 0 ] && [ -n "$SUBSYSLOCK" ] && touch $SUBSYSLOCK
 	;;
     *)
 	usage 1
