Make SHOREWALL_COMPILER=perl explicit in shorewall.conf Send SHOREWALL_COMPILER errors to STDERR
Signed-off-by: Tom Eastep <teastep@shorewall.net>

git-svn-id: https://shorewall.svn.sourceforge.net/svnroot/shorewall/trunk@9822 fbd18981-670d-0410-9b5c-8dc0c1a9a2bb

diff --git a/Shorewall/shorewall b/Shorewall/shorewall
--- a/Shorewall/shorewall
+++ b/Shorewall/shorewall
@@ -216,11 +216,11 @@ get_config() {
 	    perl|Perl)
 		;;
 	    shell|Shell)
-		echo "   ERROR: SHOREWALL_COMPILER=shell is no longer supported"
+		echo "   ERROR: SHOREWALL_COMPILER=shell is no longer supported" >&2
 		exit 2
 		;;
 	    *)
-		echo "   ERROR: Invalid value ($SHOREWALL_COMPILER) for SHOREWALL_COMPILER"
+		echo "   ERROR: Invalid value ($SHOREWALL_COMPILER) for SHOREWALL_COMPILER" >&2
 		exit 2
 		;;
 	esac
