Import tc4shorewall into project
git-svn-id: https://shorewall.svn.sourceforge.net/svnroot/shorewall/trunk@2611 fbd18981-670d-0410-9b5c-8dc0c1a9a2bb

diff --git a/Shorewall/tcstart b/Shorewall/tcstart
--- a/Shorewall/tcstart
+++ b/Shorewall/tcstart
@@ -12,6 +12,14 @@ if [ -z "$COMMAND" ]; then
 
 	. $FUNCTIONS
 
+elif [ "$COMMAND" = restore ]; then
+        cd /etc/shorewall
+	SHOREWALL_DIR=.
+fi
+
+if [ -z "$COMMAND" -o "$COMMAND" = restore ]; then
+	run_tc() { tc $@; }
+	fatal_error() { echo "   ERROR: $@" >&2; exit 2; }
 	TMP_DIR=
 	TMP_DIR=$(mktempdir)
 fi
