improve an error message
git-svn-id: https://shorewall.svn.sourceforge.net/svnroot/shorewall/trunk@4968 fbd18981-670d-0410-9b5c-8dc0c1a9a2bb

diff --git a/Shorewall-lite/shorewall-lite b/Shorewall-lite/shorewall-lite
--- a/Shorewall-lite/shorewall-lite
+++ b/Shorewall-lite/shorewall-lite
@@ -520,7 +520,7 @@ for library in $LIBRARIES; do
     if [ -f $library ]; then
 	. $library
     else
-	echo "$library does not exist!" >&2
+	echo "Installation error: $library does not exist!" >&2
 	exit 2
     fi
 done
