Shorewall 1.4.10f
git-svn-id: https://shorewall.svn.sourceforge.net/svnroot/shorewall/trunk@1420 fbd18981-670d-0410-9b5c-8dc0c1a9a2bb

diff --git a/Lrp/sbin/shorewall b/Lrp/sbin/shorewall
--- a/Lrp/sbin/shorewall
+++ b/Lrp/sbin/shorewall
@@ -109,7 +109,7 @@ showfirstchain() # $1 = name of chain
     /^Chain/	 {if ( prnt == 1 ) { rslt=0; exit 0; }; };\
     /Chain '$1'/ { prnt=1; }; \
 		 { if (prnt == 1)  print; };\
-    END		 { exit rslt; }' /tmp/chains-$$
+    END		 { exit rslt; }' $TMPFILE
 }
 
 showchain() # $1 = name of chain
@@ -124,7 +124,7 @@ showchain() # $1 = name of chain
 	/^$|^ pkts/  { next; };\
 	/^Chain/     {if ( prnt == 1 ) exit; };\
 	/Chain '$1'/ { prnt=1; };\
-		     { if (prnt == 1)  print; }' /tmp/chains-$$
+		     { if (prnt == 1)  print; }' $TMPFILE
     fi
 }
 
@@ -169,14 +169,18 @@ get_config() {
 #
 display_chains()
 {
-    trap "rm -f /tmp/chains-$$; exit 1" 1 2 3 4 5 6 9
+    trap "rm -f $TMPFILE; exit 1" 1 2 3 4 5 6 9
 
     if [ "$haveawk" = "Yes" ]; then
 	#
 	# Send the output to a temporary file since ash craps if we try to store
 	# the output in a variable.
 	#
-	iptables -L -n -v > /tmp/chains-$$
+	TMPFILE=$(mktempfile)
+
+	[ -n "$TMPFILE" ] || { echo "Cannot create a temporary file" >&2; exit 2; }
+
+	iptables -L -n -v >> $TMPFILE
 
 	clear
 	echo "$banner `date`"
@@ -197,7 +201,7 @@ display_chains()
 	echo "Input Chains"
 	echo
 
-	chains=`grep '^Chain.*_[in|fwd]' /tmp/chains-$$ | cut -d' ' -f 2`
+	chains=`grep '^Chain.*_[in|fwd]' $TMPFILE | cut -d' ' -f 2`
 
 	for chain in $chains; do
 	    showchain $chain
@@ -207,7 +211,7 @@ display_chains()
 
 	for zone in $zones; do
 
-	    if [ -n "`grep "^Chain \.*${zone}" /tmp/chains-$$`" ] ; then
+	    if [ -n "`grep "^Chain \.*${zone}" $TMPFILE`" ] ; then
 		clear
 		echo "$banner `date`"
 		echo
@@ -257,7 +261,7 @@ display_chains()
 	showchain dynamic
 	timed_read
 
-	qt rm -f /tmp/chains-$$
+	qt rm -f $TMPFILE
     else
 	iptables -L -n -v
 	timed_read
@@ -373,8 +377,8 @@ monitor_firewall() # $1 = timeout -- if negative, prompt each time that
 
 
     if qt which awk; then
-	TMP_DIR=/tmp/shorewall-$$
-	mkdir $TMP_DIR
+	TMP_DIR=$(mktempdir)
+	[ -n "$TMP_DIR" ] || { echo "Unable to create a temporary directory" >&2; exit 2; }
 	haveawk=Yes
 	determine_zones
 	rm -rf $TMP_DIR
@@ -897,7 +901,7 @@ case "$1" in
 	[ $# -ne 1 ] && usage 1
 	mutex_on
 	if qt iptables -L shorewall -n; then
-	    [ -d /var/lib/shorewall ] || mkdir /var/lib/shorewall
+	    [ -d /var/lib/shorewall ] || { mkdir /var/lib/shorewall; chmod 700 /var/lib/shorewall; }
 
 	    if iptables -L dynamic -n > /var/lib/shorewall/save; then
 		echo "Dynamic Rules Saved"
