Apply Thomas D's fix for error message in shorewall-init
Signed-off-by: Tom Eastep <teastep@shorewall.net>

diff --git a/Shorewall-init/shorewall-init b/Shorewall-init/shorewall-init
--- a/Shorewall-init/shorewall-init
+++ b/Shorewall-init/shorewall-init
@@ -50,7 +50,7 @@ if [ -f "$SYSCONFDIR/shorewall-init" ]; then
 	exit 1
     fi
 else
-    echo "ERROR: /etc/sysconfig/shorewall-init not found" >&2
+    echo "ERROR: ${SYSCONFDIR}/shorewall-init not found" >&2
     exit 1
 fi
 
